site_name: Fortran programming
site_url: https://github.com/WonyoungCho/Fortran
site_description: Tutorial review of Fortran
repo_url: https://github.com/WonyoungCho/Fortran/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Fortran:
        - 'Introduction' : 'README.md'
    - OpenMP:
        - 'Introduction' : 'openmp_int.md'
        - 'Example' : 'openmp.md'

theme: readthedocs
